### ISSUE TITLE
Can you make this available as a pod?

### ISSUE THREAD

**Issue by hawflakes** [AgoraIO/AgoraRtcEngine_iOS#27] opened 2022-09-28 18:30 UTC
Have had CI issues pulling the official pod download link being flaky. Would it be possible to add a podspec so this can be used instead?

**Comment by maxxfrazer** [comment] 2022-09-29 15:30
Which version of the pod are you trying to pull? There was an issue with the hosting server (download.agora.io) a couple of weeks ago, but that should be resolved now.

**Comment by hawflakes** [comment] 2022-09-29 17:28
3.x is there a place to see system status updates for `download.agora.io`? If we can't be notified we can't really rely on it for builds whereas there's a higher bar for GitHub and ability to check status.

**Comment by maxxfrazer** [comment] 2022-09-29 18:16
Hosting on GitHub is great IMO, and that's actually how the [first version of this package](https://github.com/AgoraIO/AgoraRtcEngine_iOS/releases/tag/3.3.0) worked when it was created. But not applicable to all the platforms we support, so we'd end up hosting iOS/macOS here, and everything else on our downloads server.

Let's see if @plutoless has any input there.

---

Which 3.x version exactly are you looking for, and when did it last have a problem (or is it constant and happening right now)?
AFAIK download.agora.io had an unusual error that was fairly quickly resolved. There's no official way to check system status other than an old fashioned ping unfortunately.

**Comment by hawflakes** [comment] 2022-09-30 18:44
Sorry for the delay, @maxxfrazer  We're currently using `3.7.0.3`!

**Comment by hawflakes** [comment] 2022-09-30 18:50
D'oh looks like we hit 10/1 National Day so it'll be a while before @plutoless will be around.

**Comment by hawflakes** [comment] 2022-10-10 18:09
@maxxfrazer @plutoless I know you guys are probably busy at RTE 2022 but would be great together an update!

**Comment by plutoless** [comment] 2022-10-12 01:18
sorry for late reply. i don't quite get the question. this sdk is already available as pod?
you can use pod 'AgoraRtcEngine_iOS', '3.7.1' in your podfile. does this answer your question？

**Comment by hawflakes** [comment] 2022-10-12 01:20
No, it doesn't quite address the issue we had. Your site was down and our builds broke. There's no way we knew of your site outage and so all we could do is make our own mirror. If you provided a podspec in this repo we'd be able to install the pod from your GitHub repo. Does that make sense?

**Comment by maxxfrazer** [comment] 2022-10-12 01:23
@plutoless looks like @hawflakes's issue was more to do with the SDK not downloading properly from downloads.agora.io when trying to install (regardless of swiftpm or cocoapods)

The issue is that this repo actually downloads from the same address:
https://github.com/AgoraIO/AgoraRtcEngine_iOS/blob/1b4cf5214d5c3d3fa5735f48ba26e26f2f75bacf/Package.swift#L25

But one solution could be uploading those as artefacts on the release with GitHub, as done with previous versions from quite a while ago such as this one:
https://github.com/AgoraIO/AgoraRtcEngine_iOS/releases/tag/3.3.0

> Note they're not added to any commit, just the release, which means it won't bloat the repository itself.

**Comment by plutoless** [comment] 2022-10-12 01:36
ok i can try talking to sdk team abt this.

**Comment by hawflakes** [comment] 2022-10-12 01:52
多谢 Orz

**Comment by hawflakes** [comment] 2022-10-27 05:00
@plutoless 🛎️  any updates?

**Comment by plutoless** [comment] 2022-10-27 11:07
@hawflakes they are still discussing this. i'll let you know once updated.

**Comment by hawflakes** [comment] 2022-10-31 23:58
@plutoless @maxxfrazer we've hit some outage again. Is there really nowhere where you post the status of downloads.agora.io? This is getting pretty old.

**Comment by plutoless** [comment] 2022-11-02 03:44
@hawflakes we are working on the github backup solution, btw, is there any chance you can provide your network information and time/logs when the outage happened so that we can investigate further with this issue?

**Comment by hawflakes** [comment] 2022-11-02 03:52
@plutoless thanks for the update. I don't have that solution as we are either building locally or using CI. I can try to dig up those CI builds that failed if that helps.

**Comment by plutoless** [comment] 2022-11-02 12:21
@hawflakes for sure it helps! would be ideal if you can provide these to help us improve availability of our global download link :)

**Comment by hawflakes** [comment] 2022-11-02 14:50
@plutoless I checked and basically all of our builds from 2022/9/15 failed in CI. They stopped failing because we switched to using our own clone.

We switched back and it's been working fine recently until about two days ago one local developer build broke trying to download it.

**Comment by hawflakes** [comment] 2022-12-06 22:02
@plutoless 已经一个多月了。请问有没有消息呢？
It's been over a month. Any updates?

**Comment by CleavoApps** [comment] 2022-12-15 07:32
Cant install agora at all SPM or Cocoapods

**Comment by hawflakes** [comment] 2023-01-18 06:49
@plutoless Happy New Year. Any news before 春节？

**Comment by arifantastic** [comment] 2023-01-25 06:02
=== January 2023 ===
`pod 'AgoraRtcEngine_iOS', '~> 4.1.0'`

**Comment by arifbd** [comment] 2023-01-25 06:08
=== January 2023 ===
`pod 'AgoraRtcEngine_iOS', '~> 4.1.0'`

**Comment by hawflakes** [comment] 2023-01-25 06:10
@arifbd yes, that works until download.agora.io goes down. This issue is asking to host the pod here on Github.

**Comment by maxxfrazer** [comment] 2023-04-12 15:48
@hawflakes have you had any problems recently with this? I'll bring it up internally again, but wanted to check-in with you on it.

**Comment by maxxfrazer** [comment] 2023-05-23 03:36
Going to close this issue - we're still considering updating the CI process to upload to GitHub, but there's a bit of reluctancy to host it on a 3rd party's servers instead of our own.

**Closed by maxxfrazer** 2023-05-23 03:36 UTC
